# Generated by Django 5.2.2 on 2025-07-04 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCrescimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('altura_cm', models.DecimalField(decimal_places=2, help_text='Altura da planta em centímetros', max_digits=5)),
                ('numero_folhas', models.PositiveIntegerField(default=0, help_text='Número de folhas da planta')),
                ('foto_planta', models.ImageField(blank=True, help_text='Uma foto da planta no dia do registro', null=True, upload_to='fotos_plantas/')),
                ('anotacoes', models.TextField(blank=True, help_text='Observações gerais sobre a planta', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
