# Generated by Django 5.2.2 on 2025-07-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registrocrescimento_data_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmidadeDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('umidade_media', models.FloatField(help_text='Umidade média registrada no dia (%)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umidade Diária',
                'verbose_name_plural': 'Umidades Diárias',
                'ordering': ['-data'],
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
